#=========== User Api ============#
### create user api endpoint
GET  http://localhost:8000/api/v1/users



### create user api endpoint
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name" : "Johna",
    "email" : "johna@email.com",
    "password" : "qwerty"
}

### create user api endpoint
POST  http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email" : "john@email.com",
    "password" : "qwerty"
}

#=========== expense Api ============#

###GET EXEPENSES
GET http://localhost:8000/api/v1/expenses
Authorization: 6279c84595e8f5b8e972e1eb


###POST EXEPENSES
POST  http://localhost:8000/api/v1/expenses
Content-Type: application/json
Authorization: 6278a4316e830d3c25563a38

{
    "name" : "Food",
    "amount" : 100,
    "date" : "2022-05-10"
}

###DELETE EXEPENSES
DELETE  http://localhost:8000/api/v1/expenses